version: '3.8'

services:


  publish:
    build:
      context: ../../..
      args:
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: publish/pypi/docker/Dockerfile
    secrets:
       - username
       - password
    volumes:
      - ../../../custom/src:${HOMEDIR}/${PACKAGE}
      - ../../../custom/pypi/setup.py:${HOMEDIR}/setup.py:ro
      - ../../../custom/pypi/MANIFEST.in:${HOMEDIR}/MANIFEST.in:ro
      - ../../../custom/pypi/__init__.py:${HOMEDIR}/${PACKAGE}/__init__.py:ro
      - ../../../custom/pypi/requirements.txt:${HOMEDIR}/${PACKAGE}/requirements.txt:ro
      - ../../../LICENSE:${HOMEDIR}/LICENSE:ro
      - ../../../README.md:${HOMEDIR}/README.md:ro
    # command: sh -c "python3 setup.py sdist bdist_wheel"
    command: sh -c "python3 setup.py sdist bdist_wheel
                 && python3 -m twine upload -u `cat /run/secrets/username` -p `cat /run/secrets/password` --repository pypi dist/*"

  # gen-req:
  #   image: pip-gen-req
  #   build:
  #     context: .
  #     dockerfile: req.dockerfile
  #     args:
  #       IMAGE: ${BASE_IMAGE}
  #       HOME: ${REQ_HOME}
  #   volumes:
  #     - $PWD/requirements:${REQ_HOME}
  #   command: sh -c "pip-compile requirements.in > requirements.txt"

secrets:
  username:
    file: ./secrets/username
  password:
    file: ./secrets/password
