name: retropath2_wrapper
channels:
  - conda-forge
dependencies:
  - brs_utils >=1.19
  - filetype
  - colored
  - freetype
  - nss
  - atk-1.0
  - at-spi2-atk
  - cups-devel-cos7-x86_64
  - xorg-libxcomposite
  - xorg-libxdamage
  - xorg-libxrandr
  - libxkbcommon-devel-cos7-x86_64
  - alsa-lib-devel-cos7-aarch64
  - libxshmfence-devel-cos7-x86_64
  - mesa-libgbm-cos7-x86_64
  - libdrm-cos7-x86_64