version: '3.8'

services:


  run:
    image: brsynth/${PACKAGE}
    build:
      context: ../..
      args:
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: run-in-env/docker/Dockerfile
    volumes:
      - ../../custom/src:${HOMEDIR}
    command: python main.py

  # gen-req:
  #   image: pip-gen-req
  #   build:
  #     context: .
  #     dockerfile: req.dockerfile
  #     args:
  #       IMAGE: ${BASE_IMAGE}
  #       HOME: ${REQ_HOME}
  #   volumes:
  #     - $PWD/requirements:${REQ_HOME}
  #   command: sh -c "pip-compile requirements.in > requirements.txt"
