version: '2.4'

services:

  retropath2:
    image: brsynth/retropath2
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: retropath2
    restart: always

networks:
  default:
    name: retropath2
