version: '2.4'

services:

  rest:
    image: brsynth/${TOOL}-rest:${MODE}
    build:
      context: .
      dockerfile: ${MODE}.dockerfile
    env_file: .env
    container_name: ${TOOL}-rest
    restart: always
    volumes:
      - $PWD/..:/home
      - $PWD/app:/REST/app
      - $PWD/conf/supervisor.conf:/CONF/supervisor.conf:ro


networks:
  default:
    name: ${TOOL}
